import EStyleSheet from 'react-native-extended-stylesheet';

export default EStyleSheet.create({
	regularStyle: {
		$themeElementWidth: '30%',
		width: '$themeElementWidth',
		minWidth: 200,
		height: 60,
		backgroundColor: '$mainColor',
		justifyContent: 'center',
		alignItems: 'center',
		borderRadius: 10,
		shadowColor: 'rgba(0, 0, 0, .16)',
		shadowOffset: { width: 0, height: 3 },
		shadowOpacity: 1,
		shadowRadius: 6,
		marginBottom: 40,
		borderColor: '#E6bb0F',
		borderWidth: 3,
	},
	answeredStyle: {
		$themeElementWidth: '30%',
		width: '$themeElementWidth',
		minWidth: 200,
		height: 60,
		backgroundColor: '#fc403f',
		justifyContent: 'center',
		alignItems: 'center',
		borderRadius: 10,
		shadowColor: 'rgba(0, 0, 0, .16)',
		shadowOffset: { width: 0, height: 3 },
		shadowOpacity: 1,
		shadowRadius: 6,
		marginBottom: 40,
		borderColor: '#E6bb0F',
		borderWidth: 3,
	},
	inModalStyle: {
		backgroundColor: 'rgba(255, 255, 255, .9)',
		justifyContent: 'space-between',
		alignItems: 'center',
		width: 420,
		height: 100,
		padding: 20,
		borderRadius: 50,
		position: 'absolute',
		shadowColor: 'rgba(0, 0, 0, .86)',
		shadowOffset: { width: 0, height: 3 },
		shadowOpacity: 1,
		shadowRadius: 15,
	},
	text: {
		backgroundColor: 'transparent',
		fontSize: 23,
		color: '$mainDarkColor',
		zIndex: 3,
	},
	icon: {
		zIndex: 2,
	},
	bg: {
		position: 'absolute',
		right: 0,
		bottom: 0,
		width: 420,
		height: 100,
		borderRadius: 50,
	},
});
